package com.sp.Admin.mapper;

import com.sp.Admin.pojo.ec_environment;
import com.sp.Admin.pojo.ec_environmentExample;
import java.util.List;

public interface ec_environmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    int insert(ec_environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    int insertSelective(ec_environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    List<ec_environment> selectByExample(ec_environmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    ec_environment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ec_environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ec_environment record);

	List<ec_environment> getNewEnvironment();
	
	List<ec_environment> getEnvironment();
}