package com.sp.Admin.mapper;

import com.sp.Admin.pojo.ec_ie;
import com.sp.Admin.pojo.ec_ieExample;
import java.util.List;

public interface ec_ieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_ie
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_ie
     *
     * @mbg.generated
     */
    int insert(ec_ie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_ie
     *
     * @mbg.generated
     */
    int insertSelective(ec_ie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_ie
     *
     * @mbg.generated
     */
    List<ec_ie> selectByExample(ec_ieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_ie
     *
     * @mbg.generated
     */
    ec_ie selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_ie
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ec_ie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_ie
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ec_ie record);

	List<ec_ie> getNewIe();
	List<ec_ie> getIe();
}