package com.sp.Admin.mapper;

import com.sp.Admin.pojo.ec_step;
import com.sp.Admin.pojo.ec_stepExample;
import java.util.List;

public interface ec_stepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_step
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_step
     *
     * @mbg.generated
     */
    int insert(ec_step record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_step
     *
     * @mbg.generated
     */
    int insertSelective(ec_step record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_step
     *
     * @mbg.generated
     */
    List<ec_step> selectByExample(ec_stepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_step
     *
     * @mbg.generated
     */
    ec_step selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_step
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ec_step record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_step
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ec_step record);

	List<ec_step> getNewStep();
	
	List<ec_step> getStep();
}