package com.sp.Admin.mapper;

import com.sp.Admin.pojo.ec_visitor;
import com.sp.Admin.pojo.ec_visitorExample;
import java.util.List;

public interface ec_visitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_visitor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_visitor
     *
     * @mbg.generated
     */
    int insert(ec_visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_visitor
     *
     * @mbg.generated
     */
    int insertSelective(ec_visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_visitor
     *
     * @mbg.generated
     */
    List<ec_visitor> selectByExample(ec_visitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_visitor
     *
     * @mbg.generated
     */
    ec_visitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_visitor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ec_visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_visitor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ec_visitor record);
    List<ec_visitor> getNewVisitor();

	List<ec_visitor> getVisitor();
}