package com.sp.Admin.pojo;

public class ec_environment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.January
     *
     * @mbg.generated
     */
    private Integer january;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.February
     *
     * @mbg.generated
     */
    private Integer february;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.March
     *
     * @mbg.generated
     */
    private Integer march;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.April
     *
     * @mbg.generated
     */
    private Integer april;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.May
     *
     * @mbg.generated
     */
    private Integer may;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.June
     *
     * @mbg.generated
     */
    private Integer june;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.July
     *
     * @mbg.generated
     */
    private Integer july;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.August
     *
     * @mbg.generated
     */
    private Integer august;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.September
     *
     * @mbg.generated
     */
    private Integer september;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.October
     *
     * @mbg.generated
     */
    private Integer october;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.November
     *
     * @mbg.generated
     */
    private Integer november;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.December
     *
     * @mbg.generated
     */
    private Integer december;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_environment.time
     *
     * @mbg.generated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.Id
     *
     * @return the value of ec_environment.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.Id
     *
     * @param id the value for ec_environment.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.type
     *
     * @return the value of ec_environment.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.type
     *
     * @param type the value for ec_environment.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.January
     *
     * @return the value of ec_environment.January
     *
     * @mbg.generated
     */
    public Integer getJanuary() {
        return january;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.January
     *
     * @param january the value for ec_environment.January
     *
     * @mbg.generated
     */
    public void setJanuary(Integer january) {
        this.january = january;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.February
     *
     * @return the value of ec_environment.February
     *
     * @mbg.generated
     */
    public Integer getFebruary() {
        return february;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.February
     *
     * @param february the value for ec_environment.February
     *
     * @mbg.generated
     */
    public void setFebruary(Integer february) {
        this.february = february;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.March
     *
     * @return the value of ec_environment.March
     *
     * @mbg.generated
     */
    public Integer getMarch() {
        return march;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.March
     *
     * @param march the value for ec_environment.March
     *
     * @mbg.generated
     */
    public void setMarch(Integer march) {
        this.march = march;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.April
     *
     * @return the value of ec_environment.April
     *
     * @mbg.generated
     */
    public Integer getApril() {
        return april;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.April
     *
     * @param april the value for ec_environment.April
     *
     * @mbg.generated
     */
    public void setApril(Integer april) {
        this.april = april;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.May
     *
     * @return the value of ec_environment.May
     *
     * @mbg.generated
     */
    public Integer getMay() {
        return may;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.May
     *
     * @param may the value for ec_environment.May
     *
     * @mbg.generated
     */
    public void setMay(Integer may) {
        this.may = may;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.June
     *
     * @return the value of ec_environment.June
     *
     * @mbg.generated
     */
    public Integer getJune() {
        return june;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.June
     *
     * @param june the value for ec_environment.June
     *
     * @mbg.generated
     */
    public void setJune(Integer june) {
        this.june = june;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.July
     *
     * @return the value of ec_environment.July
     *
     * @mbg.generated
     */
    public Integer getJuly() {
        return july;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.July
     *
     * @param july the value for ec_environment.July
     *
     * @mbg.generated
     */
    public void setJuly(Integer july) {
        this.july = july;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.August
     *
     * @return the value of ec_environment.August
     *
     * @mbg.generated
     */
    public Integer getAugust() {
        return august;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.August
     *
     * @param august the value for ec_environment.August
     *
     * @mbg.generated
     */
    public void setAugust(Integer august) {
        this.august = august;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.September
     *
     * @return the value of ec_environment.September
     *
     * @mbg.generated
     */
    public Integer getSeptember() {
        return september;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.September
     *
     * @param september the value for ec_environment.September
     *
     * @mbg.generated
     */
    public void setSeptember(Integer september) {
        this.september = september;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.October
     *
     * @return the value of ec_environment.October
     *
     * @mbg.generated
     */
    public Integer getOctober() {
        return october;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.October
     *
     * @param october the value for ec_environment.October
     *
     * @mbg.generated
     */
    public void setOctober(Integer october) {
        this.october = october;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.November
     *
     * @return the value of ec_environment.November
     *
     * @mbg.generated
     */
    public Integer getNovember() {
        return november;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.November
     *
     * @param november the value for ec_environment.November
     *
     * @mbg.generated
     */
    public void setNovember(Integer november) {
        this.november = november;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.December
     *
     * @return the value of ec_environment.December
     *
     * @mbg.generated
     */
    public Integer getDecember() {
        return december;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.December
     *
     * @param december the value for ec_environment.December
     *
     * @mbg.generated
     */
    public void setDecember(Integer december) {
        this.december = december;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_environment.time
     *
     * @return the value of ec_environment.time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_environment.time
     *
     * @param time the value for ec_environment.time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}