package com.sp.Admin.pojo;

import java.util.ArrayList;
import java.util.List;

public class ec_environmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public ec_environmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andJanuaryIsNull() {
            addCriterion("January is null");
            return (Criteria) this;
        }

        public Criteria andJanuaryIsNotNull() {
            addCriterion("January is not null");
            return (Criteria) this;
        }

        public Criteria andJanuaryEqualTo(Integer value) {
            addCriterion("January =", value, "january");
            return (Criteria) this;
        }

        public Criteria andJanuaryNotEqualTo(Integer value) {
            addCriterion("January <>", value, "january");
            return (Criteria) this;
        }

        public Criteria andJanuaryGreaterThan(Integer value) {
            addCriterion("January >", value, "january");
            return (Criteria) this;
        }

        public Criteria andJanuaryGreaterThanOrEqualTo(Integer value) {
            addCriterion("January >=", value, "january");
            return (Criteria) this;
        }

        public Criteria andJanuaryLessThan(Integer value) {
            addCriterion("January <", value, "january");
            return (Criteria) this;
        }

        public Criteria andJanuaryLessThanOrEqualTo(Integer value) {
            addCriterion("January <=", value, "january");
            return (Criteria) this;
        }

        public Criteria andJanuaryIn(List<Integer> values) {
            addCriterion("January in", values, "january");
            return (Criteria) this;
        }

        public Criteria andJanuaryNotIn(List<Integer> values) {
            addCriterion("January not in", values, "january");
            return (Criteria) this;
        }

        public Criteria andJanuaryBetween(Integer value1, Integer value2) {
            addCriterion("January between", value1, value2, "january");
            return (Criteria) this;
        }

        public Criteria andJanuaryNotBetween(Integer value1, Integer value2) {
            addCriterion("January not between", value1, value2, "january");
            return (Criteria) this;
        }

        public Criteria andFebruaryIsNull() {
            addCriterion("February is null");
            return (Criteria) this;
        }

        public Criteria andFebruaryIsNotNull() {
            addCriterion("February is not null");
            return (Criteria) this;
        }

        public Criteria andFebruaryEqualTo(Integer value) {
            addCriterion("February =", value, "february");
            return (Criteria) this;
        }

        public Criteria andFebruaryNotEqualTo(Integer value) {
            addCriterion("February <>", value, "february");
            return (Criteria) this;
        }

        public Criteria andFebruaryGreaterThan(Integer value) {
            addCriterion("February >", value, "february");
            return (Criteria) this;
        }

        public Criteria andFebruaryGreaterThanOrEqualTo(Integer value) {
            addCriterion("February >=", value, "february");
            return (Criteria) this;
        }

        public Criteria andFebruaryLessThan(Integer value) {
            addCriterion("February <", value, "february");
            return (Criteria) this;
        }

        public Criteria andFebruaryLessThanOrEqualTo(Integer value) {
            addCriterion("February <=", value, "february");
            return (Criteria) this;
        }

        public Criteria andFebruaryIn(List<Integer> values) {
            addCriterion("February in", values, "february");
            return (Criteria) this;
        }

        public Criteria andFebruaryNotIn(List<Integer> values) {
            addCriterion("February not in", values, "february");
            return (Criteria) this;
        }

        public Criteria andFebruaryBetween(Integer value1, Integer value2) {
            addCriterion("February between", value1, value2, "february");
            return (Criteria) this;
        }

        public Criteria andFebruaryNotBetween(Integer value1, Integer value2) {
            addCriterion("February not between", value1, value2, "february");
            return (Criteria) this;
        }

        public Criteria andMarchIsNull() {
            addCriterion("March is null");
            return (Criteria) this;
        }

        public Criteria andMarchIsNotNull() {
            addCriterion("March is not null");
            return (Criteria) this;
        }

        public Criteria andMarchEqualTo(Integer value) {
            addCriterion("March =", value, "march");
            return (Criteria) this;
        }

        public Criteria andMarchNotEqualTo(Integer value) {
            addCriterion("March <>", value, "march");
            return (Criteria) this;
        }

        public Criteria andMarchGreaterThan(Integer value) {
            addCriterion("March >", value, "march");
            return (Criteria) this;
        }

        public Criteria andMarchGreaterThanOrEqualTo(Integer value) {
            addCriterion("March >=", value, "march");
            return (Criteria) this;
        }

        public Criteria andMarchLessThan(Integer value) {
            addCriterion("March <", value, "march");
            return (Criteria) this;
        }

        public Criteria andMarchLessThanOrEqualTo(Integer value) {
            addCriterion("March <=", value, "march");
            return (Criteria) this;
        }

        public Criteria andMarchIn(List<Integer> values) {
            addCriterion("March in", values, "march");
            return (Criteria) this;
        }

        public Criteria andMarchNotIn(List<Integer> values) {
            addCriterion("March not in", values, "march");
            return (Criteria) this;
        }

        public Criteria andMarchBetween(Integer value1, Integer value2) {
            addCriterion("March between", value1, value2, "march");
            return (Criteria) this;
        }

        public Criteria andMarchNotBetween(Integer value1, Integer value2) {
            addCriterion("March not between", value1, value2, "march");
            return (Criteria) this;
        }

        public Criteria andAprilIsNull() {
            addCriterion("April is null");
            return (Criteria) this;
        }

        public Criteria andAprilIsNotNull() {
            addCriterion("April is not null");
            return (Criteria) this;
        }

        public Criteria andAprilEqualTo(Integer value) {
            addCriterion("April =", value, "april");
            return (Criteria) this;
        }

        public Criteria andAprilNotEqualTo(Integer value) {
            addCriterion("April <>", value, "april");
            return (Criteria) this;
        }

        public Criteria andAprilGreaterThan(Integer value) {
            addCriterion("April >", value, "april");
            return (Criteria) this;
        }

        public Criteria andAprilGreaterThanOrEqualTo(Integer value) {
            addCriterion("April >=", value, "april");
            return (Criteria) this;
        }

        public Criteria andAprilLessThan(Integer value) {
            addCriterion("April <", value, "april");
            return (Criteria) this;
        }

        public Criteria andAprilLessThanOrEqualTo(Integer value) {
            addCriterion("April <=", value, "april");
            return (Criteria) this;
        }

        public Criteria andAprilIn(List<Integer> values) {
            addCriterion("April in", values, "april");
            return (Criteria) this;
        }

        public Criteria andAprilNotIn(List<Integer> values) {
            addCriterion("April not in", values, "april");
            return (Criteria) this;
        }

        public Criteria andAprilBetween(Integer value1, Integer value2) {
            addCriterion("April between", value1, value2, "april");
            return (Criteria) this;
        }

        public Criteria andAprilNotBetween(Integer value1, Integer value2) {
            addCriterion("April not between", value1, value2, "april");
            return (Criteria) this;
        }

        public Criteria andMayIsNull() {
            addCriterion("May is null");
            return (Criteria) this;
        }

        public Criteria andMayIsNotNull() {
            addCriterion("May is not null");
            return (Criteria) this;
        }

        public Criteria andMayEqualTo(Integer value) {
            addCriterion("May =", value, "may");
            return (Criteria) this;
        }

        public Criteria andMayNotEqualTo(Integer value) {
            addCriterion("May <>", value, "may");
            return (Criteria) this;
        }

        public Criteria andMayGreaterThan(Integer value) {
            addCriterion("May >", value, "may");
            return (Criteria) this;
        }

        public Criteria andMayGreaterThanOrEqualTo(Integer value) {
            addCriterion("May >=", value, "may");
            return (Criteria) this;
        }

        public Criteria andMayLessThan(Integer value) {
            addCriterion("May <", value, "may");
            return (Criteria) this;
        }

        public Criteria andMayLessThanOrEqualTo(Integer value) {
            addCriterion("May <=", value, "may");
            return (Criteria) this;
        }

        public Criteria andMayIn(List<Integer> values) {
            addCriterion("May in", values, "may");
            return (Criteria) this;
        }

        public Criteria andMayNotIn(List<Integer> values) {
            addCriterion("May not in", values, "may");
            return (Criteria) this;
        }

        public Criteria andMayBetween(Integer value1, Integer value2) {
            addCriterion("May between", value1, value2, "may");
            return (Criteria) this;
        }

        public Criteria andMayNotBetween(Integer value1, Integer value2) {
            addCriterion("May not between", value1, value2, "may");
            return (Criteria) this;
        }

        public Criteria andJuneIsNull() {
            addCriterion("June is null");
            return (Criteria) this;
        }

        public Criteria andJuneIsNotNull() {
            addCriterion("June is not null");
            return (Criteria) this;
        }

        public Criteria andJuneEqualTo(Integer value) {
            addCriterion("June =", value, "june");
            return (Criteria) this;
        }

        public Criteria andJuneNotEqualTo(Integer value) {
            addCriterion("June <>", value, "june");
            return (Criteria) this;
        }

        public Criteria andJuneGreaterThan(Integer value) {
            addCriterion("June >", value, "june");
            return (Criteria) this;
        }

        public Criteria andJuneGreaterThanOrEqualTo(Integer value) {
            addCriterion("June >=", value, "june");
            return (Criteria) this;
        }

        public Criteria andJuneLessThan(Integer value) {
            addCriterion("June <", value, "june");
            return (Criteria) this;
        }

        public Criteria andJuneLessThanOrEqualTo(Integer value) {
            addCriterion("June <=", value, "june");
            return (Criteria) this;
        }

        public Criteria andJuneIn(List<Integer> values) {
            addCriterion("June in", values, "june");
            return (Criteria) this;
        }

        public Criteria andJuneNotIn(List<Integer> values) {
            addCriterion("June not in", values, "june");
            return (Criteria) this;
        }

        public Criteria andJuneBetween(Integer value1, Integer value2) {
            addCriterion("June between", value1, value2, "june");
            return (Criteria) this;
        }

        public Criteria andJuneNotBetween(Integer value1, Integer value2) {
            addCriterion("June not between", value1, value2, "june");
            return (Criteria) this;
        }

        public Criteria andJulyIsNull() {
            addCriterion("July is null");
            return (Criteria) this;
        }

        public Criteria andJulyIsNotNull() {
            addCriterion("July is not null");
            return (Criteria) this;
        }

        public Criteria andJulyEqualTo(Integer value) {
            addCriterion("July =", value, "july");
            return (Criteria) this;
        }

        public Criteria andJulyNotEqualTo(Integer value) {
            addCriterion("July <>", value, "july");
            return (Criteria) this;
        }

        public Criteria andJulyGreaterThan(Integer value) {
            addCriterion("July >", value, "july");
            return (Criteria) this;
        }

        public Criteria andJulyGreaterThanOrEqualTo(Integer value) {
            addCriterion("July >=", value, "july");
            return (Criteria) this;
        }

        public Criteria andJulyLessThan(Integer value) {
            addCriterion("July <", value, "july");
            return (Criteria) this;
        }

        public Criteria andJulyLessThanOrEqualTo(Integer value) {
            addCriterion("July <=", value, "july");
            return (Criteria) this;
        }

        public Criteria andJulyIn(List<Integer> values) {
            addCriterion("July in", values, "july");
            return (Criteria) this;
        }

        public Criteria andJulyNotIn(List<Integer> values) {
            addCriterion("July not in", values, "july");
            return (Criteria) this;
        }

        public Criteria andJulyBetween(Integer value1, Integer value2) {
            addCriterion("July between", value1, value2, "july");
            return (Criteria) this;
        }

        public Criteria andJulyNotBetween(Integer value1, Integer value2) {
            addCriterion("July not between", value1, value2, "july");
            return (Criteria) this;
        }

        public Criteria andAugustIsNull() {
            addCriterion("August is null");
            return (Criteria) this;
        }

        public Criteria andAugustIsNotNull() {
            addCriterion("August is not null");
            return (Criteria) this;
        }

        public Criteria andAugustEqualTo(Integer value) {
            addCriterion("August =", value, "august");
            return (Criteria) this;
        }

        public Criteria andAugustNotEqualTo(Integer value) {
            addCriterion("August <>", value, "august");
            return (Criteria) this;
        }

        public Criteria andAugustGreaterThan(Integer value) {
            addCriterion("August >", value, "august");
            return (Criteria) this;
        }

        public Criteria andAugustGreaterThanOrEqualTo(Integer value) {
            addCriterion("August >=", value, "august");
            return (Criteria) this;
        }

        public Criteria andAugustLessThan(Integer value) {
            addCriterion("August <", value, "august");
            return (Criteria) this;
        }

        public Criteria andAugustLessThanOrEqualTo(Integer value) {
            addCriterion("August <=", value, "august");
            return (Criteria) this;
        }

        public Criteria andAugustIn(List<Integer> values) {
            addCriterion("August in", values, "august");
            return (Criteria) this;
        }

        public Criteria andAugustNotIn(List<Integer> values) {
            addCriterion("August not in", values, "august");
            return (Criteria) this;
        }

        public Criteria andAugustBetween(Integer value1, Integer value2) {
            addCriterion("August between", value1, value2, "august");
            return (Criteria) this;
        }

        public Criteria andAugustNotBetween(Integer value1, Integer value2) {
            addCriterion("August not between", value1, value2, "august");
            return (Criteria) this;
        }

        public Criteria andSeptemberIsNull() {
            addCriterion("September is null");
            return (Criteria) this;
        }

        public Criteria andSeptemberIsNotNull() {
            addCriterion("September is not null");
            return (Criteria) this;
        }

        public Criteria andSeptemberEqualTo(Integer value) {
            addCriterion("September =", value, "september");
            return (Criteria) this;
        }

        public Criteria andSeptemberNotEqualTo(Integer value) {
            addCriterion("September <>", value, "september");
            return (Criteria) this;
        }

        public Criteria andSeptemberGreaterThan(Integer value) {
            addCriterion("September >", value, "september");
            return (Criteria) this;
        }

        public Criteria andSeptemberGreaterThanOrEqualTo(Integer value) {
            addCriterion("September >=", value, "september");
            return (Criteria) this;
        }

        public Criteria andSeptemberLessThan(Integer value) {
            addCriterion("September <", value, "september");
            return (Criteria) this;
        }

        public Criteria andSeptemberLessThanOrEqualTo(Integer value) {
            addCriterion("September <=", value, "september");
            return (Criteria) this;
        }

        public Criteria andSeptemberIn(List<Integer> values) {
            addCriterion("September in", values, "september");
            return (Criteria) this;
        }

        public Criteria andSeptemberNotIn(List<Integer> values) {
            addCriterion("September not in", values, "september");
            return (Criteria) this;
        }

        public Criteria andSeptemberBetween(Integer value1, Integer value2) {
            addCriterion("September between", value1, value2, "september");
            return (Criteria) this;
        }

        public Criteria andSeptemberNotBetween(Integer value1, Integer value2) {
            addCriterion("September not between", value1, value2, "september");
            return (Criteria) this;
        }

        public Criteria andOctoberIsNull() {
            addCriterion("October is null");
            return (Criteria) this;
        }

        public Criteria andOctoberIsNotNull() {
            addCriterion("October is not null");
            return (Criteria) this;
        }

        public Criteria andOctoberEqualTo(Integer value) {
            addCriterion("October =", value, "october");
            return (Criteria) this;
        }

        public Criteria andOctoberNotEqualTo(Integer value) {
            addCriterion("October <>", value, "october");
            return (Criteria) this;
        }

        public Criteria andOctoberGreaterThan(Integer value) {
            addCriterion("October >", value, "october");
            return (Criteria) this;
        }

        public Criteria andOctoberGreaterThanOrEqualTo(Integer value) {
            addCriterion("October >=", value, "october");
            return (Criteria) this;
        }

        public Criteria andOctoberLessThan(Integer value) {
            addCriterion("October <", value, "october");
            return (Criteria) this;
        }

        public Criteria andOctoberLessThanOrEqualTo(Integer value) {
            addCriterion("October <=", value, "october");
            return (Criteria) this;
        }

        public Criteria andOctoberIn(List<Integer> values) {
            addCriterion("October in", values, "october");
            return (Criteria) this;
        }

        public Criteria andOctoberNotIn(List<Integer> values) {
            addCriterion("October not in", values, "october");
            return (Criteria) this;
        }

        public Criteria andOctoberBetween(Integer value1, Integer value2) {
            addCriterion("October between", value1, value2, "october");
            return (Criteria) this;
        }

        public Criteria andOctoberNotBetween(Integer value1, Integer value2) {
            addCriterion("October not between", value1, value2, "october");
            return (Criteria) this;
        }

        public Criteria andNovemberIsNull() {
            addCriterion("November is null");
            return (Criteria) this;
        }

        public Criteria andNovemberIsNotNull() {
            addCriterion("November is not null");
            return (Criteria) this;
        }

        public Criteria andNovemberEqualTo(Integer value) {
            addCriterion("November =", value, "november");
            return (Criteria) this;
        }

        public Criteria andNovemberNotEqualTo(Integer value) {
            addCriterion("November <>", value, "november");
            return (Criteria) this;
        }

        public Criteria andNovemberGreaterThan(Integer value) {
            addCriterion("November >", value, "november");
            return (Criteria) this;
        }

        public Criteria andNovemberGreaterThanOrEqualTo(Integer value) {
            addCriterion("November >=", value, "november");
            return (Criteria) this;
        }

        public Criteria andNovemberLessThan(Integer value) {
            addCriterion("November <", value, "november");
            return (Criteria) this;
        }

        public Criteria andNovemberLessThanOrEqualTo(Integer value) {
            addCriterion("November <=", value, "november");
            return (Criteria) this;
        }

        public Criteria andNovemberIn(List<Integer> values) {
            addCriterion("November in", values, "november");
            return (Criteria) this;
        }

        public Criteria andNovemberNotIn(List<Integer> values) {
            addCriterion("November not in", values, "november");
            return (Criteria) this;
        }

        public Criteria andNovemberBetween(Integer value1, Integer value2) {
            addCriterion("November between", value1, value2, "november");
            return (Criteria) this;
        }

        public Criteria andNovemberNotBetween(Integer value1, Integer value2) {
            addCriterion("November not between", value1, value2, "november");
            return (Criteria) this;
        }

        public Criteria andDecemberIsNull() {
            addCriterion("December is null");
            return (Criteria) this;
        }

        public Criteria andDecemberIsNotNull() {
            addCriterion("December is not null");
            return (Criteria) this;
        }

        public Criteria andDecemberEqualTo(Integer value) {
            addCriterion("December =", value, "december");
            return (Criteria) this;
        }

        public Criteria andDecemberNotEqualTo(Integer value) {
            addCriterion("December <>", value, "december");
            return (Criteria) this;
        }

        public Criteria andDecemberGreaterThan(Integer value) {
            addCriterion("December >", value, "december");
            return (Criteria) this;
        }

        public Criteria andDecemberGreaterThanOrEqualTo(Integer value) {
            addCriterion("December >=", value, "december");
            return (Criteria) this;
        }

        public Criteria andDecemberLessThan(Integer value) {
            addCriterion("December <", value, "december");
            return (Criteria) this;
        }

        public Criteria andDecemberLessThanOrEqualTo(Integer value) {
            addCriterion("December <=", value, "december");
            return (Criteria) this;
        }

        public Criteria andDecemberIn(List<Integer> values) {
            addCriterion("December in", values, "december");
            return (Criteria) this;
        }

        public Criteria andDecemberNotIn(List<Integer> values) {
            addCriterion("December not in", values, "december");
            return (Criteria) this;
        }

        public Criteria andDecemberBetween(Integer value1, Integer value2) {
            addCriterion("December between", value1, value2, "december");
            return (Criteria) this;
        }

        public Criteria andDecemberNotBetween(Integer value1, Integer value2) {
            addCriterion("December not between", value1, value2, "december");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(String value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(String value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(String value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(String value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(String value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(String value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLike(String value) {
            addCriterion("time like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotLike(String value) {
            addCriterion("time not like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<String> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<String> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(String value1, String value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(String value1, String value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ec_environment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ec_environment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}