package com.sp.Admin.pojo;

public class ec_users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.user_nickname
     *
     * @mbg.generated
     */
    private String userNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.user_regtime
     *
     * @mbg.generated
     */
    private String userRegtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.user_regip
     *
     * @mbg.generated
     */
    private String userRegip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.user_ltlogip
     *
     * @mbg.generated
     */
    private String userLtlogip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.user_token
     *
     * @mbg.generated
     */
    private String userToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_users.user_portraituri
     *
     * @mbg.generated
     */
    private String userPortraituri;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.id
     *
     * @return the value of ec_users.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.id
     *
     * @param id the value for ec_users.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.user_id
     *
     * @return the value of ec_users.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.user_id
     *
     * @param userId the value for ec_users.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.user_password
     *
     * @return the value of ec_users.user_password
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.user_password
     *
     * @param userPassword the value for ec_users.user_password
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.user_nickname
     *
     * @return the value of ec_users.user_nickname
     *
     * @mbg.generated
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.user_nickname
     *
     * @param userNickname the value for ec_users.user_nickname
     *
     * @mbg.generated
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.user_phone
     *
     * @return the value of ec_users.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.user_phone
     *
     * @param userPhone the value for ec_users.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.user_regtime
     *
     * @return the value of ec_users.user_regtime
     *
     * @mbg.generated
     */
    public String getUserRegtime() {
        return userRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.user_regtime
     *
     * @param userRegtime the value for ec_users.user_regtime
     *
     * @mbg.generated
     */
    public void setUserRegtime(String userRegtime) {
        this.userRegtime = userRegtime == null ? null : userRegtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.user_regip
     *
     * @return the value of ec_users.user_regip
     *
     * @mbg.generated
     */
    public String getUserRegip() {
        return userRegip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.user_regip
     *
     * @param userRegip the value for ec_users.user_regip
     *
     * @mbg.generated
     */
    public void setUserRegip(String userRegip) {
        this.userRegip = userRegip == null ? null : userRegip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.user_ltlogip
     *
     * @return the value of ec_users.user_ltlogip
     *
     * @mbg.generated
     */
    public String getUserLtlogip() {
        return userLtlogip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.user_ltlogip
     *
     * @param userLtlogip the value for ec_users.user_ltlogip
     *
     * @mbg.generated
     */
    public void setUserLtlogip(String userLtlogip) {
        this.userLtlogip = userLtlogip == null ? null : userLtlogip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.user_token
     *
     * @return the value of ec_users.user_token
     *
     * @mbg.generated
     */
    public String getUserToken() {
        return userToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.user_token
     *
     * @param userToken the value for ec_users.user_token
     *
     * @mbg.generated
     */
    public void setUserToken(String userToken) {
        this.userToken = userToken == null ? null : userToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_users.user_portraituri
     *
     * @return the value of ec_users.user_portraituri
     *
     * @mbg.generated
     */
    public String getUserPortraituri() {
        return userPortraituri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_users.user_portraituri
     *
     * @param userPortraituri the value for ec_users.user_portraituri
     *
     * @mbg.generated
     */
    public void setUserPortraituri(String userPortraituri) {
        this.userPortraituri = userPortraituri == null ? null : userPortraituri.trim();
    }
}