package com.sp.Admin.pojo;

public class ec_visitor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.monday
     *
     * @mbg.generated
     */
    private Integer monday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.tuesday
     *
     * @mbg.generated
     */
    private Integer tuesday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.wednesday
     *
     * @mbg.generated
     */
    private Integer wednesday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.thursday
     *
     * @mbg.generated
     */
    private Integer thursday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.Friday
     *
     * @mbg.generated
     */
    private Integer friday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.saturday
     *
     * @mbg.generated
     */
    private Integer saturday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.Sunday
     *
     * @mbg.generated
     */
    private Integer sunday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_visitor.time
     *
     * @mbg.generated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.Id
     *
     * @return the value of ec_visitor.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.Id
     *
     * @param id the value for ec_visitor.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.type
     *
     * @return the value of ec_visitor.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.type
     *
     * @param type the value for ec_visitor.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.monday
     *
     * @return the value of ec_visitor.monday
     *
     * @mbg.generated
     */
    public Integer getMonday() {
        return monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.monday
     *
     * @param monday the value for ec_visitor.monday
     *
     * @mbg.generated
     */
    public void setMonday(Integer monday) {
        this.monday = monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.tuesday
     *
     * @return the value of ec_visitor.tuesday
     *
     * @mbg.generated
     */
    public Integer getTuesday() {
        return tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.tuesday
     *
     * @param tuesday the value for ec_visitor.tuesday
     *
     * @mbg.generated
     */
    public void setTuesday(Integer tuesday) {
        this.tuesday = tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.wednesday
     *
     * @return the value of ec_visitor.wednesday
     *
     * @mbg.generated
     */
    public Integer getWednesday() {
        return wednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.wednesday
     *
     * @param wednesday the value for ec_visitor.wednesday
     *
     * @mbg.generated
     */
    public void setWednesday(Integer wednesday) {
        this.wednesday = wednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.thursday
     *
     * @return the value of ec_visitor.thursday
     *
     * @mbg.generated
     */
    public Integer getThursday() {
        return thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.thursday
     *
     * @param thursday the value for ec_visitor.thursday
     *
     * @mbg.generated
     */
    public void setThursday(Integer thursday) {
        this.thursday = thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.Friday
     *
     * @return the value of ec_visitor.Friday
     *
     * @mbg.generated
     */
    public Integer getFriday() {
        return friday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.Friday
     *
     * @param friday the value for ec_visitor.Friday
     *
     * @mbg.generated
     */
    public void setFriday(Integer friday) {
        this.friday = friday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.saturday
     *
     * @return the value of ec_visitor.saturday
     *
     * @mbg.generated
     */
    public Integer getSaturday() {
        return saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.saturday
     *
     * @param saturday the value for ec_visitor.saturday
     *
     * @mbg.generated
     */
    public void setSaturday(Integer saturday) {
        this.saturday = saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.Sunday
     *
     * @return the value of ec_visitor.Sunday
     *
     * @mbg.generated
     */
    public Integer getSunday() {
        return sunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.Sunday
     *
     * @param sunday the value for ec_visitor.Sunday
     *
     * @mbg.generated
     */
    public void setSunday(Integer sunday) {
        this.sunday = sunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_visitor.time
     *
     * @return the value of ec_visitor.time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_visitor.time
     *
     * @param time the value for ec_visitor.time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}